// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB14PCuchPwSZ6YJYteDS4euaFnR0Zeb_w',
    appId: '1:938351542884:web:647941afcd8cbee6dd9571',
    messagingSenderId: '938351542884',
    projectId: 'fashion-store-956c8',
    authDomain: 'fashion-store-956c8.firebaseapp.com',
    storageBucket: 'fashion-store-956c8.appspot.com',
    measurementId: 'G-REJZY2RC1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDthlZZRMP-EKvln-EdCrZ6rZZGEZgTr0',
    appId: '1:938351542884:android:df8e46ac5cac06acdd9571',
    messagingSenderId: '938351542884',
    projectId: 'fashion-store-956c8',
    storageBucket: 'fashion-store-956c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIlwV6_Himk5mgNc6NZ1awh-NXeTEPXHw',
    appId: '1:938351542884:ios:3be2873b96b26ededd9571',
    messagingSenderId: '938351542884',
    projectId: 'fashion-store-956c8',
    storageBucket: 'fashion-store-956c8.appspot.com',
    iosClientId: '938351542884-dhoj6hdu8h3g15oqv3o4sb0c3512ri0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
